- name: promt names
  hosts: localhost
  become: yes
  vars_prompt:
    - name: USERNAME
      prompt: Please enter your name
      private: false
    - name: PASSWORD
      prompt: Please enter your password
      private: true
  tasks:
    - name: print variables
      ansible.builtin.debug:
       msg "username:{{USERNAME}} 
            password:{{PASSWORD}}"
    